[build]
  functions = "api"
  publish = "dist"
  command = "yarn build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF api public scripts netlify.toml package.json vite.config.js"

[[redirects]]
  from = "/wallpaper/*"
  to = "/.netlify/functions/wallpaper/:splat"
  status = 200
