name: Daily Sync

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn

      - name: Run sync script
        run: node scripts/sync.js

      - name: Commit changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin master
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated sync"
          git push
